-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- return {
--   "LazyVim/LazyVim",
--   config = function()
--     vim.cmd("autocmd BufNewFile,BufRead *.md set filetype=markdown")
--   end,
-- }
